//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJob
    {
        public int NumID { get; set; }
        public string chrLocalNumber { get; set; }
        public string chrONLNumber { get; set; }
        public string chrName { get; set; }
        public string chrDivision { get; set; }
        public string chrCountry { get; set; }
        public string chrProductType { get; set; }
        public string chrSampleType { get; set; }
        public string chrIPG { get; set; }
        public string chrClient { get; set; }
        public bool blKeyClient { get; set; }
        public Nullable<int> intComplexity { get; set; }
        public Nullable<System.DateTime> dtmCreated { get; set; }
        public bool blNeedCleaning { get; set; }
        public bool blNeedTable { get; set; }
        public bool blNeedCoding { get; set; }
        public string inteProjectID { get; set; }
    }
}
