//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProducerPermission
    {
        public int ID { get; set; }
        public string chrUserID { get; set; }
        public Nullable<bool> blAuto { get; set; }
        public Nullable<bool> blCPG { get; set; }
        public Nullable<bool> blEtailer { get; set; }
        public Nullable<bool> blFinance { get; set; }
        public Nullable<bool> blMedia { get; set; }
        public Nullable<bool> blRetailerPlus { get; set; }
        public Nullable<bool> blTechTelco { get; set; }
        public Nullable<bool> blNIP { get; set; }
        public Nullable<bool> blME { get; set; }
    }
}
