//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuotationSummary
    {
        public int ID { get; set; }
        public string chrQuotationNumber { get; set; }
        public string chrMethod { get; set; }
        public string chrWaveNo { get; set; }
        public string chrProjectName { get; set; }
        public Nullable<System.DateTime> dtmCreated { get; set; }
        public string memClarify { get; set; }
        public Nullable<double> dblClarifyTimeSpent { get; set; }
        public string chrFresh { get; set; }
        public Nullable<System.DateTime> dtmRFQMonth { get; set; }
        public string chrOffice { get; set; }
        public string chrClient { get; set; }
        public string chrVertical { get; set; }
        public string chrVertical2 { get; set; }
        public string chrMethod2 { get; set; }
        public string memDesignOptimization { get; set; }
        public string memBenifit { get; set; }
        public Nullable<int> intSampleSize { get; set; }
        public Nullable<double> dblLOI { get; set; }
        public Nullable<double> dblIR { get; set; }
        public string chrFrequency { get; set; }
        public string memTargetGroupDefinition { get; set; }
        public Nullable<int> intOrders { get; set; }
        public Nullable<int> intRevisions { get; set; }
        public string chrCSContact { get; set; }
        public string chrHubSPOC { get; set; }
        public string chrProducer { get; set; }
        public Nullable<double> dblDAOOP { get; set; }
        public Nullable<double> dblTotalDACost { get; set; }
        public Nullable<double> dblGOCost { get; set; }
        public Nullable<double> dblOralRevenue { get; set; }
        public Nullable<System.DateTime> dtmBKFMRelease { get; set; }
        public string chrStatusUpdate { get; set; }
        public Nullable<System.DateTime> dtmLastUpdated { get; set; }
        public string chrTrackingOrNot { get; set; }
        public Nullable<double> dblVendorOOP { get; set; }
        public Nullable<double> dblVendorOutsource { get; set; }
        public Nullable<double> dblPreRecruit { get; set; }
        public Nullable<double> dblIncentive { get; set; }
        public Nullable<double> dblTravel { get; set; }
        public Nullable<double> dblVenue { get; set; }
        public Nullable<double> dblProductPurchase { get; set; }
        public Nullable<double> dblCentralTraining { get; set; }
        public Nullable<double> dblOther { get; set; }
        public Nullable<double> dblQC3rdParty { get; set; }
        public Nullable<double> dblQCTemp { get; set; }
        public Nullable<double> dblCoupon { get; set; }
        public Nullable<double> dblCentralTraining2 { get; set; }
        public Nullable<double> dblFWTemp { get; set; }
        public Nullable<double> dblTnE { get; set; }
        public Nullable<double> dblQuotationOther { get; set; }
        public Nullable<double> dblNielsenOOP { get; set; }
        public Nullable<double> dblTotalExternalCost { get; set; }
        public Nullable<double> dblTotalInternalCost { get; set; }
    }
}
